# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appsecurity', '__first__'),
        ('student', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appsecurity.UserProfile')),
                ('website', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=32)),
                ('oncampus', models.BooleanField(default=True)),
                ('address1', models.CharField(blank=True, max_length=32)),
                ('address2', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(blank=True, max_length=16)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zipcode', models.CharField(blank=True, max_length=5)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('preferredstudents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
