# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='startdate',
            field=models.DateField(),
        ),
    ]
